project:
  type: book
  output-dir: docs

book:
  title: "BMS"
  author: 
    - "James R Perkins"
    - "Federico Garcia Criado"
  date: "7/26/2024"
  chapters:
    - index.qmd
    - reintro_a_r.qmd
    - hpo_redes1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

